--- 

- name: Install NginX
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Change default port for NginX (2)
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
  notify: restart nginx

- name: Ensure NginX is enabled and running
  service:
    name: nginx
    state: restarted
    enabled: yes
    
