---


- name: Make sure docker-python RPM is installed
  yum:
      name: docker-python
      state: present

- name: Make sure system is up to date
  yum:
      name: '*'
      state: latest

- name: Install docker
  yum:
      name: docker

- name: Install Python-pip
  yum: 
      name: "{{ item }}"
      state: present
  with_items:
      - python-pip

- name: Upgrade pip
  command: pip install --upgrade pip

- name: Install required PyPi Pachages
  pip:
      name: "{{ item.name }}"
      state: present
  with_items:
      - { name: docker, version: 2.0.0 }
      - { name: docker-py, version: 1.10.6 }
      #- six>=1.4.0

- name: Start docker service and enable it
  service:
      name: docker
      state: restarted
      enabled: yes

- name: Include variables
  include_vars: main.yml

- name: Create Container
  docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    ports:
      - "{{ src_port }}:{{ dest_port }}"
    volumes:
      - "{{ src_vol }}:{{ dest_vol }}"
    privileged: "{{ privileged }}"

- name: Create Systemd file as docker-{{ name }}.service
  template:
    src: systemd.j2
    dest: /etc/systemd/system/docker-{{ name }}.service


- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and Enable docker-{{ name }}.service
  service:
    name: docker-{{ name }}
    state: started
    enabled: yes

- name: check container status
  command: docker ps
  register: result
- debug: var=result.stdout
