---

- name: Ensure System is all Patched up
  yum:
    name: "*"
    state: latest 

- name: Ensure local MySQL directory exists
  file:
    path: /var/lib/mysql
    state: directory
    mode: 0755

- name: Command to start MySQL Docker Container
  shell: docker run -d --name prod_mysql -p 3306:3306 -v /var/lib/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=tiger mysql/mysql-server:latest
