---
- name: Set up MariaDB yum repository
  template:
    src: mariadb.repo.j2
    dest: "{{ mariadb_repo_directory }}/mariadb.repo"

- name: Install MariaDB 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-devel
    - python-devel
    - libffi-devel
    - openssl-devel
    - python-pip
    - mysql-devel
    - libevent-devel

- name: Pip Install MySQL-Python
  command: pip install mysql-python

- name: Update MySQL root password for root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template:
    src: root.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
