---
- name: Ensure Firewall is running
  service:
    name: firewalld
    state: started

- name: Open Port 80 and 443
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https

- name: Open port 8080
  command: firewall-cmd --permanent --add-port=8080/tcp
  notify: restart firewalld
