---
- name: Install packages needed for ALL servers
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - expect
    - vim
    - python-pip
    - tree
    - psmisc
    - python-pip

- name: Install pexpect using pip
  command: pip install pexpect

- name: Install Development Group of packages
  yum:
    name: "@Development tools"
    state: present
