---
- name: Install packages needed for ALL servers
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - expect
    - vim
    - python-pip
    - tree
    - psmisc

- name: Install pexpect using pip
  command: pip install pexpect
