---

- name: Install common user software requirements
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - vim
    - expect
    - python-pip
  tags: AddingUsers
    
- name: Create groups needed
  group: 
    name: "{{ item }}"
    state: present
  with_items:
    - developers
    - admins
  tags: AddingUsers

- name: Generate passwords
  #shell: python -c 'import crypt; print crypt.crypt("{{ password }}", "$6$random_salt")'
  shell: python -c "from passlib.hash import sha512_crypt; print sha512_crypt.encrypt('<password>')"
  register: genpass
  tags: AddingUsers

- name: Creating user "{{ username }}"
  user:
    name: "{{ username }}"
    #password: "{{ genpass.stdout }}"
    password: "{{ upassword |password_hash(‘sha512’) }}"
    groups: admins, developers
    update_password: on_create
  tags: AddingUsers

- name: Expiring passwords immediately for "{{ username }}"
  command: chage -d0 "{{ username }}" 
  tags: AddingUsers

- name: Deleting user "{{ username }}"
  user: 
    name: "{{ username }}"
    state: absent
    remove: yes
  tags: RemoveUsers
