---
- name: Install PHP
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-mysql
    - php-fpm
  notify: restart apache

- name: Copy Sample PHP page to document root
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
  notify: restart apache
